### ISSUE TITLE
Compatibility with empty chapters

### ISSUE THREAD

**Issue by nagim** [DomainDrivenArchitecture/gitbook-plugin-expandable-chapters#4]
Hi,

I really like your plugin, great work!

I use the [ungrey](https://github.com/BlaXpirit/gitbook-plugin-ungrey) plugin to make visible and clickable empty chapters.
It looks like this in the SUMMARY.md:
```
* New Section
  * [Chapter 1](chapter1.md)
```
Unfortunately, your plugin does not mark it as expandable (see the screenshot).
![expand_plugin](https://cloud.githubusercontent.com/assets/16205115/11895610/81e71ca4-a580-11e5-93c9-fd37c1780949.jpg)

Could you please have a look if you could make it compatible? It would increase usability of the TOC greatly.

Thank you very much in advance!
Imre

**Comment by chrisjake** [comment]
I would love this as well! I've swapped over to toggle chapters but I like this one much more.

**Comment by jerger** [comment]
Hi, we don't need empty chapters. So I will not implement this enhancement immediately ...
But it's open source, so I would appreciate any pull request :-)
